In [5]:
from src.utils import read_data, get_events, segment_events
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [6]:
path = 'C:/Users/Benjamin/Documents/Code/precipitations/data/dataframes/2020_1.pkl'
data = pd.read_pickle(path)

In [7]:
data.to_hdf('C:/Users/Benjamin/Documents/Code/precipitations/data/dataframes/2020_1.h5', key='df', mode='w')

ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.

In [ ]:
def plot_time_series_with_events(ts, events):
    plt.figure(figsize=(12, 6))
    plt.plot(ts, label='Time Series',)  # Plot the time series data
    
    # Highlight each event with a shaded area
    for start, end in events:
        plt.axvspan(start, end, color='yellow', alpha=0.3)
    
    # Adding labels and title for clarity
    plt.xlabel('Time (*5 minutes)')
    plt.ylabel('Value')
    plt.title('TS avec événement segmenté')
    plt.legend()
    plt.grid(True)
    plt.show()

In [ ]:
raw_data[(raw_data != 0)]

In [ ]:
def read_data(year, month, day):
    path = f'data/raw_data/{year:04d}/'
    file_name = f'RR_IDF300x300_{year:04d}{month:02d}{day:02d}.npy'
    full_path = path + file_name
    try:
        raw_data = np.load(full_path) / 100.0
        raw_data[raw_data < 0] = np.nan
        #raw_data[raw_data < 0] = 0 # ça changerait quoi ?
    except FileNotFoundError:
        raise FileNotFoundError(f"The file {full_path} does not exist.")
    return raw_data

def read_data_raww(year, month, day):
    path = f'data/raw_data/{year:04d}/'
    file_name = f'RR_IDF300x300_{year:04d}{month:02d}{day:02d}.npy'
    full_path = path + file_name
    try:
        raw_data = np.load(full_path) / 100.0
        #raw_data[raw_data < 0] = np.nan
        #raw_data[raw_data < 0] = 0 # ça changerait quoi ?
    except FileNotFoundError:
        raise FileNotFoundError(f"The file {full_path} does not exist.")
    return raw_data

In [ ]:
raw_data = read_data(2021, 1, 10)
ts = np.zeros((288))
for i in range(300):
    for j in range(300):
        ts += raw_data[:, i, j]

# Use the previously defined function to segment events
event_tuples = segment_events(ts)

# Plot the time series with highlighted events
plot_time_series_with_events(ts, event_tuples)

In [ ]:
ts

In [ ]:
np.isnan(ts[44])

In [32]:
import pandas as pd

df = pd.read_pickle('C:/Users/Benjamin/Documents/Code/precipitations/data/dataframes/2017_1.pkl')

In [31]:
df

,year,month,day,i,j,start_time_relative,end_time_relative,start_time_absolute,end_time_absolute,duration,max_intensity,mean_intensity,variance,percentage_null
0,2020,6,1,103,44,209,209,209,209,1,0.24,0.24,0.0000,0.000000
1,2020,6,1,103,44,224,224,224,224,1,0.36,0.36,0.0000,0.000000
2,2020,6,1,104,41,219,221,219,221,3,1.08,0.44,0.2144,0.333333
3,2020,6,1,104,41,227,227,227,227,1,1.56,1.56,0.0000,0.000000
4,2020,6,1,135,45,140,143,140,143,4,1.20,0.42,0.2412,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4649738,2020,6,30,296,23,210,210,8562,8562,1,0.24,0.24,0.0000,0.000000
4649739,2020,6,30,297,21,211,211,8563,8563,1,0.24,0.24,0.0000,0.000000
4649740,2020,6,30,297,23,210,210,8562,8562,1,0.24,0.24,0.0000,0.000000
4649741,2020,6,30,298,22,211,211,8563,8563,1,0.24,0.24,0.0000,0.000000
4649742,2020,6,30,298,278,60,60,8412,8412,1,0.12,0.12,0.0000,0.000000

In [2]:
df.to_csv("2020_6.csv")

In [ ]:
def event_stats(raw_data, i, j, start_time, duration):
    events = raw_data[start_time:start_time+duration, i, j]
    events = events[~np.isnan(events)]
    return duration, np.max(events), np.mean(events), np.var(events), 1 - np.count_nonzero(events) / duration

In [33]:
# read all df in data/dataframes and merge into a single df

import os
import pandas as pd

path = 'C:/Users/Benjamin/Documents/Code/precipitations/data/dataframes/'
files = os.listdir(path)
dfs = []
"""for file in files:
    dfs.append(pd.read_pickle(path + file))
df = pd.concat(dfs)
"""

'for file in files:\n    dfs.append(pd.read_pickle(path + file))\ndf = pd.concat(dfs)\n'

In [36]:
files = [k for k in files if "2017" in k and ".pkl" in k]

In [37]:
files

['2017_1.pkl',
 '2017_10.pkl',
 '2017_11.pkl',
 '2017_12.pkl',
 '2017_2.pkl',
 '2017_3.pkl',
 '2017_4.pkl',
 '2017_5.pkl',
 '2017_6.pkl',
 '2017_7.pkl',
 '2017_8.pkl',
 '2017_9.pkl']

In [38]:
dfs = []
for file in files:
    dfs.append(pd.read_pickle(path + file))
df = pd.concat(dfs)
df.reset_index(drop=True, inplace=True)
df

,year,month,day,i,j,start_time_relative,end_time_relative,start_time_absolute,end_time_absolute,duration,max_intensity,mean_intensity,variance,percentage_null
0,2017,1,1,0,0,134,135,134,135,2,0.24,0.180000,0.003600,0.000000
1,2017,1,1,0,0,233,258,233,258,26,1.32,0.360000,0.089723,0.038462
2,2017,1,1,0,0,274,276,274,276,3,0.36,0.200000,0.012800,0.000000
3,2017,1,1,0,1,136,136,136,136,1,0.12,0.120000,0.000000,0.000000
4,2017,1,1,0,1,234,258,234,258,25,1.32,0.345600,0.165105,0.280000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62700601,2017,9,30,299,298,129,130,8481,8482,2,0.36,0.360000,0.000000,0.000000
62700602,2017,9,30,299,298,168,171,8520,8523,4,0.12,0.090000,0.002700,0.250000
62700603,2017,9,30,299,299,56,83,8408,8435,28,22.44,3.518571,25.400627,0.000000
62700604,2017,9,30,299,299,96,123,8448,8475,28,3.47,1.520714,1.348978,0.107143
62700605,2017,9,30,299,299,129,130,8481,8482,2,0.36,0.360000,0.000000,0.000000

In [39]:
#save to csv without index
df.to_csv("2017.csv", index=False)

In [14]:
df = pd.read_csv("2020.csv")

,Unnamed: 0,year,month,day,i,j,start_time_relative,end_time_relative,start_time_absolute,end_time_absolute,duration,max_intensity,mean_intensity,variance,percentage_null
0,0,2020,1,1,0,102,127,127,127,127,1,0.24,0.240,0.000000,0.000
1,1,2020,1,1,0,106,151,151,151,151,1,0.24,0.240,0.000000,0.000
2,2,2020,1,1,0,107,148,151,148,151,4,0.36,0.210,0.017100,0.250
3,3,2020,1,1,0,108,148,151,148,151,4,0.36,0.210,0.017100,0.250
4,4,2020,1,1,0,109,147,150,147,150,4,0.36,0.240,0.021600,0.250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62512414,3540759,2020,9,30,299,251,66,73,8418,8425,8,0.24,0.135,0.012375,0.375
62512415,3540760,2020,9,30,299,252,69,72,8421,8424,4,0.24,0.240,0.000000,0.000
62512416,3540761,2020,9,30,299,253,69,72,8421,8424,4,0.24,0.240,0.000000,0.000
62512417,3540762,2020,9,30,299,254,70,71,8422,8423,2,0.24,0.240,0.000000,0.000
62512418,3540763,2020,9,30,299,255,70,71,8422,8423,2,0.12,0.120,0.000000,0.000

In [23]:
import sqlite3
# Create your connection.
cnx = sqlite3.connect('features.db')

In [24]:
df = pd.read_csv("2020_6.csv")

In [25]:
df.to_sql('2020', cnx)

4649743

In [28]:
#make some basic queries on the SQLite db

query = "SELECT * FROM '2020' WHERE i = 0 AND j = 0"
df = pd.read_sql_query(query, cnx)

In [29]:
df

,index,Unnamed: 0,year,month,day,i,j,start_time_relative,end_time_relative,start_time_absolute,end_time_absolute,duration,max_intensity,mean_intensity,variance,percentage_null
0,2673,2673,2020,6,3,0,0,144,177,720,753,34,0.96,0.448235,0.051932,0.000000
1,2674,2674,2020,6,3,0,0,287,287,863,863,1,0.12,0.120000,0.000000,0.000000
2,223816,223816,2020,6,4,0,0,0,46,864,910,47,1.08,0.388085,0.070598,0.106383
3,574218,574218,2020,6,5,0,0,26,33,1178,1185,8,0.48,0.225000,0.026775,0.250000
4,574219,574219,2020,6,5,0,0,68,80,1220,1232,13,0.60,0.203077,0.031867,0.230769
5,1025439,1025439,2020,6,6,0,0,1,9,1441,1449,9,0.96,0.280000,0.083200,0.222222
6,1025440,1025440,2020,6,6,0,0,176,199,1616,1639,24,0.48,0.170000,0.016700,0.166667
7,1025441,1025441,2020,6,6,0,0,254,254,1694,1694,1,0.24,0.240000,0.000000,0.000000
8,1389007,1389007,2020,6,8,0,0,110,119,2126,2135,10,0.24,0.108000,0.009936,0.400000
9,1528228,1528228,2020,6,9,0,0,70,71,2374,2375,2,0.12,0.120000,0.000000,0.000000
10,1530913,1530913,2020,6,10,0,0,69,72,2661,2664,4,0.36,0.240000,0.007200,0.000000
11,1530914,1530914,2020,6,10,0,0,118,144,2710,2736,27,4.19,1.265926,0.892728,0.000000
12,1530915,1530915,2020,6,10,0,0,156,174,2748,2766,19,1.08,0.517895,0.063743,0.052632
13,1530916,1530916,2020,6,10,0,0,187,189,2779,2781,3,0.48,0.320000,0.022400,0.000000
14,1629881,1629881,2020,6,11,0,0,230,238,3110,3118,9,9.36,3.066667,9.107556,0.000000
15,1922117,1922117,2020,6,12,0,0,94,97,3262,3265,4,1.92,1.020000,0.471600,0.000000
16,1922118,1922118,2020,6,12,0,0,109,139,3277,3307,31,4.68,1.834194,1.196592,0.000000
17,1922119,1922119,2020,6,12,0,0,160,162,3328,3330,3,0.36,0.240000,0.009600,0.000000
18,1922120,1922120,2020,6,12,0,0,178,179,3346,3347,2,5.88,4.260000,2.624400,0.000000
19,1922121,1922121,2020,6,12,0,0,186,187,3354,3355,2,1.32,1.020000,0.090000,0.000000
20,2306244,2306244,2020,6,13,0,0,181,184,3637,3640,4,0.48,0.210000,0.031500,0.250000
21,2306245,2306245,2020,6,13,0,0,190,207,3646,3663,18,1.56,0.226667,0.131022,0.444444
22,2757787,2757787,2020,6,16,0,0,192,193,4512,4513,2,0.12,0.120000,0.000000,0.000000
23,3380731,3380731,2020,6,19,0,0,63,82,5247,5266,20,4.32,1.031000,1.132329,0.150000
24,3380732,3380732,2020,6,19,0,0,95,99,5279,5283,5,0.60,0.288000,0.032256,0.000000
25,3380733,3380733,2020,6,19,0,0,235,237,5419,5421,3,0.36,0.240000,0.009600,0.000000
26,3560090,3560090,2020,6,21,0,0,20,20,5780,5780,1,0.12,0.120000,0.000000,0.000000
27,3560091,3560091,2020,6,21,0,0,41,44,5801,5804,4,0.72,0.390000,0.045900,0.000000
28,3560092,3560092,2020,6,21,0,0,51,53,5811,5813,3,0.96,0.600000,0.067200,0.000000
29,3769548,3769548,2020,6,25,0,0,281,284,7193,7196,4,1.44,0.870000,0.139500,0.000000
30,3819129,3819129,2020,6,26,0,0,14,14,7214,7214,1,0.12,0.120000,0.000000,0.000000
31,3819130,3819130,2020,6,26,0,0,20,28,7220,7228,9,34.32,9.986667,123.772089,0.000000
32,4062903,4062903,2020,6,27,0,0,62,71,7550,7559,10,1.08,0.468000,0.064656,0.000000
33,4062904,4062904,2020,6,27,0,0,133,138,7621,7626,6,0.24,0.080000,0.012800,0.666667
34,4355525,4355525,2020,6,28,0,0,100,109,7876,7885,10,0.84,0.348000,0.096336,0.300000
35,4355526,4355526,2020,6,28,0,0,117,117,7893,7893,1,0.60,0.600000,0.000000,0.000000
36,4588436,4588436,2020,6,30,0,0,174,175,8526,8527,2,0.60,0.540000,0.003600,0.000000
37,4588437,4588437,2020,6,30,0,0,247,249,8599,8601,3,1.20,0.720000,0.201600,0.000000
38,4588438,4588438,2020,6,30,0,0,258,287,8610,8639,30,1.79,0.459667,0.231510,0.300000